### ISSUE TITLE
Excellent tool, thank you! How do I increase the number of activities that are downloaded?

### ISSUE THREAD

**Issue by wesraynbirdtilbury** [Cloudy17g35/strava-api#1]
It looks like the number of activities is limited to 30 - please could you advise on how to increase this?

**Comment by Cloudy17g35** [comment]
Hi, glad that you found this tool useful!

Recently had the same problem - wanted to fetch more activities - i found out that you can get up to 200 activities using **per_page** query param in GET request to the endpoint **/athlete/activities**

I already implemented this, so you can simply pull from this repo and rerun the program.

In the case you have more that 200 activities - i would play with the **page** param (that was the case for me - i needed to copy page 1 activities and part of page 2 activities and create one csv from these two datasets to get my complete data)

I believe that it should be more optimal way to do that - but strava API documentation doesn't provide many details:
<img width="592" alt="Screenshot 2024-02-17 at 16 47 47" src="https://github.com/Cloudy17g35/strava-api/assets/79964602/54c4458a-70ac-4ca2-b14d-0c4fe3e8a952">
